passing apps in an array

diff --git a/.github/workflows/azure-spring-app-management.yml b/.github/workflows/azure-spring-app-management.yml
--- a/.github/workflows/azure-spring-app-management.yml
+++ b/.github/workflows/azure-spring-app-management.yml
@@ -13,7 +13,7 @@ on:
           - restart
       app_name:
         type: string
-        description: 'Name of the Azure Spring App (Use "ALL" to apply action to all apps)'
+        description: 'Name of the Azure Spring App (Use "ALL" for all apps, or comma-separated list for multiple apps)'
         required: true
 
 jobs:
@@ -32,6 +32,9 @@ jobs:
         run: |
           if [ "${{ github.event.inputs.app_name }}" == "ALL" ]; then
             app_names=$(az spring app list --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "[].name" -o tsv)
+          elif [[ "${{ github.event.inputs.app_name }}" == *","* ]]; then
+            IFS=',' read -r -a app_name_array <<< "${{ github.event.inputs.app_name }}"
+            app_names="${app_name_array[@]}"
           else
             app_names="${{ github.event.inputs.app_name }}"
           fi
@@ -58,7 +61,7 @@ jobs:
                 if [ "$current_status" == "Running" ]; then
                   az spring app restart --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" &
                 elif [ "$current_status" == "Stopped" ]; then
-                  echo "Warning: Cannot restart the app '$app_name' because it is already stopped."
+                  echo "Warning: Cannot restart the app '$app_name' because it is stopped."
                 fi
                 ;;
               *)
@@ -70,6 +73,7 @@ jobs:
 
       - name: Check for errors
         run: |
+          wait
           if [ $? -ne 0 ]; then
             echo "An error occurred while executing the action on the app."
             exit 1
@@ -77,37 +81,40 @@ jobs:
         shell: bash
 
   validate-app-status:
-      runs-on: self-hosted
-      needs: manage-spring-app
-      steps:
-        - name: Login to Azure
-          uses: azure/login@v1
-          with:
-            creds: ${{ secrets.AZURE_CREDENTIALS }}
-  
-        - name: Wait for apps to start/stop/restart
-          run: sleep 30  # Wait for 5 minutes
-          shell: bash
-  
-        - name: Validate app status
-          run: |
-            if [ "${{ github.event.inputs.app_name }}" == "ALL" ]; then
-              app_names=$(az spring app list --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "[].name" -o tsv)
-            else
-              app_names="${{ github.event.inputs.app_name }}"
-            fi
+    runs-on: self-hosted
+    needs: manage-spring-app
+    steps:
+      - name: Login to Azure
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-            for app_name in $app_names; do
-              status=$(az spring app show --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "properties.activeDeployment.properties.status" -o tsv)
-              if [ $? -eq 0 ]; then
-                if [ -z "$status" ]; then
-                  echo "App $app_name status: Not started/stopped yet."
-                else
-                  echo "App $app_name status: $status"
-                fi
+      - name: Wait for apps to start/stop/restart
+        run: sleep 300  # Adjusted to wait for 5 minutes
+        shell: bash
+
+      - name: Validate app status
+        run: |
+          if [ "${{ github.event.inputs.app_name }}" == "ALL" ]; then
+            app_names=$(az spring app list --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "[].name" -o tsv)
+          elif [[ "${{ github.event.inputs.app_name }}" == *","* ]]; then
+            IFS=',' read -r -a app_name_array <<< "${{ github.event.inputs.app_name }}"
+            app_names="${app_name_array[@]}"
+          else
+            app_names="${{ github.event.inputs.app_name }}"
+          fi
+
+          for app_name in $app_names; do
+            status=$(az spring app show --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "properties.activeDeployment.properties.status" -o tsv)
+            if [ $? -eq 0 ]; then
+              if [ -z "$status" ]; then
+                echo "App $app_name status: Not started/stopped yet."
               else
-                echo "Failed to get status for app $app_name"
-                exit 1
+                echo "App $app_name status: $status"
               fi
-            done
-          shell: bash
+            else
+              echo "Failed to get status for app $app_name"
+              exit 1
+            fi
+          done
+        shell: bash
