code fix

diff --git a/.github/workflows/azure-spring-app-management.yml b/.github/workflows/azure-spring-app-management.yml
--- a/.github/workflows/azure-spring-app-management.yml
+++ b/.github/workflows/azure-spring-app-management.yml
@@ -28,7 +28,7 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-      - name: Execute action on app(s)
+      - name: Execute action on app
         run: |
           if [ "${{ github.event.inputs.app_name }}" == "ALL" ]; then
             app_names=$(az spring app list --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "[].name" -o tsv)
@@ -47,6 +47,14 @@ jobs:
           done
         shell: bash
 
+      - name: Check for errors
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "An error occurred while executing the action on the app."
+            exit 1
+          fi
+        shell: bash
+
   validate-app-status:
     runs-on: self-hosted
     needs: manage-spring-app
@@ -55,11 +63,11 @@ jobs:
         uses: azure/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
-
+  
       - name: Wait for apps to start/stop/restart
         run: sleep 300  # Wait for 5 minutes
         shell: bash
-
+  
       - name: Validate app status
         run: |
           if [ "${{ github.event.inputs.app_name }}" == "ALL" ]; then
@@ -67,9 +75,11 @@ jobs:
           else
             app_names="${{ github.event.inputs.app_name }}"
           fi
-
+  
           for app_name in $app_names; do
             status=$(az spring app show --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "properties.activeDeployment.properties.status" -o tsv)
             if [ $? -eq 0 ]; then
               if [ -z "$status" ]; then
-                echo "App $
+                echo "App $app_name status: Not started/stopped yet."
+              else
+                echo "App $app
